### PR TITLE
Relicensing as AGPL

### PR DESCRIPTION
**Pull request by linuskendall**
This PR relicenses this repo as AGPL and makes all further contributions to this repo fall under AGPL. Client libraries and protobuf proto files will continue to be licensed under the Apache license.

**Motivation**

We want to make sure that this gRPC interface gets utilised in a standardised way across the Solana ecosystem. It is important that any user that builds against this gRPC interface has a choice of many compatible providers to use. Therefore we desire that anyone who seeks to provide a hosted version of this gRPC interface to downstream users should also make their modifications to the gRPC interface open source so they can be adopted by other users of this plugin.

Client libraries and proto files remain under the Apache license. This means that anyone building this into their own source code as a consumer of the gRPC interface has no obligations to publish the source of their client code. You are free to build clients for this gRPC interface with any license you prefer, and choose to publish it or not.

Likewise, anyone who wants to use the proto files to build another server side software that is compatible with the protobufs provided through this gRPC interface  is free to do so.

**Does this apply retroactively?**

No, any previous version of this plugin would still be licensed by the original Apache license. This license will only cover future contributions to this repo. 

**What if I have contributed code to this repo?**

If you have contributed code to this repo, we hope you would be happy to accept this new license! If you have any concerns, please comment in this thread and hopefully we can address those. However, if you feel that you do not want to accept this new license, then we will remove your code from any future versions of this repo. This code removal will be included in this PR so that the newly licensed repo will not contain your code. You still own copyright to your code and have the full right to reject this license change.

**Does this repo have copyright assignment?**

No, and this PR does not introduce copyright assignment. The copyright for the code in this repo belongs to the individuals (or organisations) that have contributed it. If you have contributed to this repo, and you accept this license change you still own copyright over your code. This means that any future licensing changes would still need your approval. 

**Who decides over the license of this repo?**

The short answer - the copyright holders. Since this repo doesn't have copyright assignment it is the individual contributors who decides on the license. The majority of the code in this repo is Copyright to Triton One, but there are other contributors to this repo too.

Triton One hosts and manages this particular copy of this repo. We will continue to host this plugin on this location using the AGPL version of the plugin. Anyone else is free to fork this repo from commit 2f924ab44fbe6c4e701850f3c272f41c8ffac97d or any previous commit. This is the last commit that we will host at this location before the licensing change. 

Be aware that any forks prior to (and including) 2f924ab44fbe6c4e701850f3c272f41c8ffac97d will be licensed Apache and any forks from this point will need to continue to be licensed Apache. If you want to use any other license for a fork, you would need to get permissions from the copyright holders.

Any forks after 2f924ab44fbe6c4e701850f3c272f41c8ffac97d in this particular repo (github.com/rpcpool/yellowstone-grpc) will be AGPL licensed (with the exceptions for the client code that remains under Apache licensing).

**I want to talk about this change**

Best is comment below here! Otherwise, ping me (linuskendall) on Twitter.

### CODE REVIEW

**Comment by linuskendall** [comment]
Reviewing commit history the people (outside of Triton) who needs to approve this: @vovkman  @godmodegalactus @grooviegermanikus

**Comment by godmodegalactus** [comment]
I think AGPL licencing like lite-rpc is correct way forward.

**Comment by fanatid** [comment]
- fix ci
- update default license in Cargo.toml

**Comment by vovkman** [comment]
good with me!

**Comment by grooviegermanikus** [comment]
good for me

**Comment by linuskendall** [comment]
Everyone asked agrees :) Thanks for quick response! Merging.

**Pull request merged**
