### PR TITLE
geyser: add worker_threads and affinity

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by andreisilviudragnea** [comment]
This PR made the project unbuildable on macOS, because [affinity](https://crates.io/crates/affinity) crate does not support macOS.

**Comment by fanatid** [comment]
is it possible to run test-validator on macOS? :thinking:

**Comment by andrei-pump** [comment]
@fanatid Yes, and I have been using it for a long time now. If you can do something to fix the master branch, it would be amazing, as for now I have to use https://github.com/rpcpool/yellowstone-grpc/releases/tag/v3.0.1+solana.2.0.18, which is the latest tag which still works on macOS.

**Comment by andreisilviudragnea** [comment]
@fanatid Yes, and I have been using it for a long time now. If you can do something to fix the master branch, it would be amazing, as for now I have to use https://github.com/rpcpool/yellowstone-grpc/releases/tag/v3.0.1+solana.2.0.18, which is the latest tag which still works on macOS.

**Pull request merged**
